### ISSUE TITLE
Move Panel code from `ipynb` to `py` (for simpler Dockerization)

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/sustainable_aviation_dashboard#6]
...the notebook ([`content/IDA Results.ipynb`](https://github.com/sustainableaviation/sustainable_aviation_dashboard/blob/main/content/IDA%20Results.ipynb)) is dead, long live the Python file (eg. `content/panel_application.ipynb`)!

This will help me complete:

- #5.

**Comment by rohrerph** [comment]
Added the Python File
